# Generated by Django 4.2.4 on 2025-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predicate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
